# -*- coding: utf-8 -*-

from . import ir_attachment
from . import freight_product
from . import mail_activity_mixin
from . import res_company
from . import res_config_settings
from . import res_country
from . import product_template
from . import harmonized_system_code
from . import container_type_size
from . import container_category
from . import container_type
from . import transport_mode
from . import uom
from . import shipment_type
from . import cargo_type
from . import consolidation_type
from . import service_mode
from . import container_service_mode
from . import freight_carrier
from . import freight_un_location
from . import freight_commodity
from . import freight_port
from . import freight_vessel_category
from . import freight_vessel
from . import contract
from . import custom_location
from . import freight_event_type
from . import res_partner_type
from . import freight_document_type
from . import res_partner
from . import freight_document_mixin
from . import haz_sub_class_code
from . import document_validation_mixin
from . import freight_warehouse_depot
from . import ir_mail_server
from . import fetchmail_server
from . import mail_thread
from . import doc_version_history
from . import freight_adjustment_ratio_type
from . import freight_measurement_basis
from . import freight_sequence
from . import models
from . import freight_shipment_tag
from . import res_bank
from . import res_partner_bank
from . import account_incoterms
from . import mixin_freight_base_company_user
from . import mixin_freight_product
from . import mixin_freight_arrival_departure_time
from . import mixin_freight_cargo_weight_volume
from . import mixin_freight_origin_destination_location
from . import haz_sub_class
from . import package_info
from . import res_users
from . import custom_master_be_type
from . import volumetric_divided_value
