# -*- coding: utf-8 -*-
{
    'name': 'CRM Prospect Lead',
    'version': '2.2',
    'author': 'Intech Creative Services Pvt. Ltd.',
    'company': 'Intech Creative Services Pvt. Ltd.',
    'category': 'CRM',
    'summary': 'CRM Prospect Lead',
    'license': 'Other proprietary',
    'description': """ CRM Prospect Lead.""",
    'depends': ['account', 'fm_sale_crm', 'crm_prospect', 'freight_base', 'phone_validation'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/lead_stage_data.xml',
        'data/opportunity_stage_data.xml',
        'data/mail_template_data.xml',
        'data/freight_sequence_data.xml',
        'data/lead_source_data.xml',
        'views/customer_visit_lines_views.xml',
        'views/crm_prospect_lead_stage_views.xml',
        'wizard/wizard_prospect_lead_status_views.xml',
        'wizard/wiz_customer_visit_report_views.xml',
        'report/customer_visit_report_action.xml',
        'report/customer_visit_report.xml',
        'views/crm_prospect_lead_views.xml',
        'views/crm_prospect_opportunity_views.xml',
        'views/crm_prospect_opportunity_stage_views.xml',
        'views/crm_prospect_views.xml',
        'views/rate_request_view.xml',
        'views/lead_source_view.xml',
        'wizard/wizard_prospect_opportunity_status_views.xml',
    ],
    'installable': True,
    'application': False
}
